/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 16
#define YY_END_OF_BUFFER 17
static yyconst short int yy_accept[150] =
    {   0,
        0,    0,   17,   15,   16,    6,    6,    6,    6,    6,
        2,    4,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,    0,    0,
       11,    0,    0,   12,    2,    0,    0,    4,   10,   10,
       10,   10,   10,   10,   10,    8,   10,   10,   10,   10,
       10,   10,    8,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,    1,    5,    0,    0,    0,   13,    0,
        0,    0,    3,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,    7,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,

        0,   11,   14,    0,   12,    9,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    4,    4,    4,    4,    6,    4,
        4,    7,    8,    4,    9,   10,   11,   12,   13,   13,
       13,   13,   13,   13,   13,   14,   14,    4,    4,    4,
        4,    4,    4,    3,   15,   15,   15,   15,   16,   15,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   17,   17,
        4,    1,    4,    3,   19,    3,   20,   21,   22,   23,

       24,   25,   26,   27,   28,   17,   29,   30,   31,   32,
       33,   34,   17,   35,   36,   37,   38,   39,   40,   41,
       42,   43,    4,    4,    4,    3,    1,    1,    1,    1,
        1,    1,    1,   44,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   44,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,   44,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[45] =
    {   0,
        1,    2,    3,    3,    4,    3,    3,    3,    1,    3,
        4,    5,    5,    5,    5,    5,    6,    6,    3,    5,
        5,    5,    5,    5,    5,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    1
    } ;

static yyconst short int yy_base[156] =
    {   0,
        0,    0,  251,  252,  252,  252,    0,    0,   33,   41,
       41,   48,    0,  212,  214,   30,   32,   34,   37,  215,
       44,  214,  222,   44,  203,  212,  210,  215,  236,  234,
       71,  232,  236,   76,   84,   89,    0,   94,    0,  200,
      212,  199,  214,  201,  207,  193,  194,  191,  191,  194,
      191,  188,    0,  187,  191,   42,  189,   48,   58,  187,
       77,   81,  192,  214,  252,  106,  211,  206,  252,  214,
      113,  116,    0,  182,  194,  189,  177,   80,  191,  189,
      185,  177,  183,  186,  172,    0,  178,  175,  164,  166,
      168,  175,  161,  159,  172,  162,  166,  170,  172,  161,

      119,  252,  252,  122,  252,    0,  161,  152,  160,  149,
      156,  150,  147,  147,  147,  144,  156,  146,  150,  155,
      153,  143,  148,  136,  148,  139,  140,  145,  136,  130,
      134,  142,  139,  141,  125,  137,  128,  131,  120,  113,
      100,   98,   88,   80,   62,   45,   54,   49,  252,  134,
      138,  140,  146,  151,   44
    } ;

static yyconst short int yy_def[156] =
    {   0,
      149,    1,  149,  149,  149,  149,  150,  151,  149,  149,
      149,  149,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  150,  149,
      149,  153,  154,  149,  149,  149,  155,  149,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  150,  149,  149,  153,  149,  149,  154,
      149,  149,  155,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,

      149,  149,  149,  149,  149,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,    0,  149,
      149,  149,  149,  149,  149
    } ;

static yyconst short int yy_nxt[297] =
    {   0,
        4,    5,    4,    6,    7,    8,    6,    6,    6,    9,
       10,   11,   12,   12,   13,   13,   13,   13,   13,   14,
       15,   16,   17,   18,   19,   20,   13,   21,   13,   22,
       13,   13,   13,   13,   23,   24,   25,   26,   27,   28,
       13,   13,   13,    6,   31,   31,   31,   32,   73,   42,
       34,   33,   35,   35,   36,   45,   43,   34,   37,   38,
       38,   38,   44,   47,   46,   48,   50,   88,   53,   51,
       57,   58,  106,   91,   49,   54,   86,   93,   89,   86,
       59,   37,   31,   31,   31,   53,   66,   31,   31,   31,
       92,   71,   94,   72,   66,   35,   35,   36,   72,   71,

       36,   36,   36,   72,   96,   38,   38,   38,   98,  148,
       99,  147,   97,  101,  101,  108,  109,  102,  102,  102,
      104,  104,   86,  146,  105,  105,  105,   31,   31,   31,
      102,  102,  102,  105,  105,  105,   29,   29,   29,   29,
       30,   30,   30,   30,   39,   39,   67,   67,   67,   53,
       67,   67,   70,   70,   70,   70,   70,  145,  144,  143,
      142,   86,  106,  106,   86,  106,  141,  106,   86,  140,
      139,   53,  138,  137,   86,  136,  135,  134,  133,  132,
       86,  131,  130,   86,  129,  128,  127,  126,  106,   53,
      125,  124,   86,  123,  122,  121,  120,  119,  118,  117,

      116,  115,  114,   86,  106,  113,  112,   86,   53,  111,
      110,   86,   53,  107,  106,   69,  103,   68,   64,  100,
       95,   90,   87,   86,   85,   53,   84,   83,   82,   81,
       80,   79,   78,   77,   76,   75,   74,   69,   68,   65,
       64,   63,   62,   61,   60,   56,   55,   52,   41,   40,
      149,    3,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149

    } ;

static yyconst short int yy_chk[297] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    9,    9,    9,   10,  155,   16,
       11,   10,   11,   11,   11,   17,   16,   12,   11,   12,
       12,   12,   16,   18,   17,   18,   19,   56,   21,   19,
       24,   24,  148,   58,   18,   21,  147,   59,   56,  146,
       24,   11,   31,   31,   31,  145,   31,   34,   34,   34,
       58,   34,   59,   35,   31,   35,   35,   35,   36,   34,

       36,   36,   36,   38,   61,   38,   38,   38,   62,  144,
       62,  143,   61,   66,   66,   78,   78,   66,   66,   66,
       71,   71,  142,  141,   71,   71,   71,   72,   72,   72,
      101,  101,  101,  104,  104,  104,  150,  150,  150,  150,
      151,  151,  151,  151,  152,  152,  153,  153,  153,  140,
      153,  153,  154,  154,  154,  154,  154,  139,  138,  137,
      136,  135,  134,  133,  132,  131,  130,  129,  128,  127,
      126,  125,  124,  123,  122,  121,  120,  119,  118,  117,
      116,  115,  114,  113,  112,  111,  110,  109,  108,  107,
      100,   99,   98,   97,   96,   95,   94,   93,   92,   91,

       90,   89,   88,   87,   85,   84,   83,   82,   81,   80,
       79,   77,   76,   75,   74,   70,   68,   67,   64,   63,
       60,   57,   55,   54,   52,   51,   50,   49,   48,   47,
       46,   45,   44,   43,   42,   41,   40,   33,   32,   30,
       29,   28,   27,   26,   25,   23,   22,   20,   15,   14,
        3,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tp3.l"
#define INITIAL 0
#line 3 "tp3.l"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>

//PROTOTIPOS
void agregarNodo(int ,char*,char*);
long conversorADecimal(char*,int);
int  representacionDigito(char,int);




int cantidadDeLineas=0;
//IDENTIFICADORES
struct nodoIdentificadores {
    char *identificador;
    char *identificadorNMayuscula;
    int cantidadIdentificadores;
    struct nodoIdentificadores *sig;
    struct nodoIdentificadores *ant;
};
typedef struct nodoIdentificadores NodoIdentificadores;
NodoIdentificadores *raizIdentificadores=NULL;

//LITERAL CADENA
struct nodoLiteralCadena {
    char *literalCadena;
    int longitud;
    struct nodoLiteralCadena *sig;
};
typedef struct nodoLiteralCadena NodoLiteralCadena;
NodoLiteralCadena *raizLiteralCadena=NULL;
NodoLiteralCadena *fondoLiteralCadena=NULL;

//PALABRAS RESERVADAS 

struct nodoPalabrasReservadas {
    char *palabraReservada;
    char *tipo; 
    struct nodoPalabrasReservadas *sig;
};
typedef struct nodoPalabrasReservadas NodoPalabrasReservadas;
NodoPalabrasReservadas *raizPalabrasReservadas=NULL;
NodoPalabrasReservadas *fondoPalabrasReservadas=NULL;


//CONSTANTES
struct nodoConstanteOctal {
    char *datoEnOctal;
    int decimal;
    struct nodoConstanteOctal *sig;
};
typedef struct nodoConstanteOctal NodoConstanteOctal;
NodoConstanteOctal *raizConstanteOctal=NULL;
NodoConstanteOctal *fondoConstanteOctal=NULL;

struct nodoConstanteHexa {
    char *datoEnHexa;
    int decimal; 
    struct nodoConstanteHexa *sig;
};
typedef struct nodoConstanteHexa NodoConstanteHexa;
NodoConstanteHexa *raizConstanteHexa=NULL;
NodoConstanteHexa *fondoConstanteHexa=NULL;


struct nodoConstanteDecimal {
    int decimal;
    struct nodoConstanteDecimal *sig;
};

typedef struct nodoConstanteDecimal NodoConstanteDecimal;
NodoConstanteDecimal *raizConstanteDecimal=NULL;
NodoConstanteDecimal *fondoConstanteDecimal=NULL;


struct nodoConstanteReal {
    float mantiza ;
    int parteEntera ;
    struct nodoConstanteReal *sig;
};
typedef struct nodoConstanteReal NodoConstanteReal;
NodoConstanteReal *raizConstanteReal=NULL;
NodoConstanteReal *fondoConstanteReal=NULL;

struct nodoConstanteCaracter {
    char *caracter;
    struct nodoConstanteCaracter *sig;
};
typedef struct nodoConstanteCaracter NodoConstanteCaracter;
NodoConstanteCaracter *raizConstanteCaracter=NULL;
NodoConstanteCaracter *fondoConstanteCaracter=NULL;

//OPERADORES/CARACTERES DE PUNTUACIÓN

struct nodoOperOCaractPunt {
    char *caracter;
    int cantidadOperOCaractPunt;
    struct nodoOperOCaractPunt *sig;
};
typedef struct nodoOperOCaractPunt NodoOperOCaractPunt;
NodoOperOCaractPunt *raizOperOCaractPunt=NULL;
NodoOperOCaractPunt *fondoOperOCaractPunt=NULL;

//COMENTARIOS 

struct nodoComentario {
    char *comentario;
    char *tipo; 
    struct nodoComentario *sig;
};
typedef struct nodoComentario NodoComentario;
NodoComentario *raizComentario=NULL;
NodoComentario *fondoComentario=NULL;


struct nodoNoReconocidos {
    char *noReconocido;
    int linea; 
    struct nodoNoReconocidos *sig;
};
typedef struct nodoNoReconocidos NodoNoReconocidos;
NodoNoReconocidos *raizNoReconocidos=NULL;
NodoNoReconocidos *fondoNoReconocidos=NULL;


long decimal;
void agregarNodo(int categoria,char* informacionNueva,char* tipo){
    if(categoria==0){  //IDENTIFICADORES
             NodoIdentificadores *nuevoNodo,*recorrido;
            char informacionNMayuscula[strlen(informacionNueva)];
            int limite=sizeof(informacionNMayuscula);
            strcpy(informacionNMayuscula,informacionNueva);
            char caracter=informacionNMayuscula[0];
            int a=0;
            while(a<=limite){
                if(caracter>=97&&caracter<=122){
                    caracter=caracter-32;
                }
                informacionNMayuscula[a]=caracter;
                caracter=informacionNMayuscula[a+1];
                a++;
                
            }
            if(raizIdentificadores==NULL){
                nuevoNodo=malloc(sizeof(NodoIdentificadores));
                nuevoNodo->identificador=strdup(informacionNueva);
                nuevoNodo->identificadorNMayuscula=strdup(informacionNMayuscula);
                nuevoNodo->cantidadIdentificadores=1;
                nuevoNodo->sig=NULL;
                nuevoNodo->ant=NULL;
                raizIdentificadores=nuevoNodo;
            }else{
                recorrido=raizIdentificadores;
                int c=0;
                while(recorrido->sig!=NULL&&strcmp(informacionNMayuscula,recorrido->identificadorNMayuscula)>=0){
                    recorrido=recorrido->sig;
                }
                int b;
                b=strcmp(informacionNMayuscula,recorrido->identificadorNMayuscula);
                if(b>0&&strcmp(informacionNueva,recorrido->identificador)!=0){
                        nuevoNodo=malloc(sizeof(NodoIdentificadores));
                        nuevoNodo->identificador=strdup(informacionNueva);
                        nuevoNodo->identificadorNMayuscula=strdup(informacionNMayuscula);
                        nuevoNodo->cantidadIdentificadores=1;
                        nuevoNodo->sig=recorrido->sig;
                        nuevoNodo->ant=recorrido;
                        recorrido->sig=nuevoNodo;
                    }else{
                        if(b==0&&strcmp(informacionNueva,recorrido->identificador)==0){
                            (recorrido->cantidadIdentificadores)++;  
                        }else{
                            nuevoNodo=malloc(sizeof(NodoIdentificadores));
                            nuevoNodo->identificador=strdup(informacionNueva);
                            nuevoNodo->identificadorNMayuscula=strdup(informacionNMayuscula);
                            nuevoNodo->cantidadIdentificadores=1;
                            nuevoNodo->sig=recorrido;
                            if(recorrido->ant==NULL){
                                raizIdentificadores=nuevoNodo;
                            }else{
                                (recorrido->ant)->sig=nuevoNodo;
                            }
                            
                        }
                    }
               
            }
    }else if(categoria==1){   //LITERA CADENA  
            NodoLiteralCadena *nuevoNodo;
            nuevoNodo=malloc(sizeof(struct nodoLiteralCadena));
            nuevoNodo->literalCadena=strdup(informacionNueva);
            nuevoNodo->longitud=strlen(informacionNueva);
            nuevoNodo->sig=NULL;
            if(raizLiteralCadena==NULL){
                raizLiteralCadena=nuevoNodo;            
            }else{
                fondoLiteralCadena->sig=nuevoNodo;
            }
            fondoLiteralCadena=nuevoNodo;
    }else if(categoria==2){   //PALABRAS RESERVADAS
           NodoPalabrasReservadas *nuevoNodo;
           nuevoNodo=malloc(sizeof(struct nodoPalabrasReservadas));
           nuevoNodo->palabraReservada=strdup(informacionNueva);
           nuevoNodo->tipo=strdup(tipo);
           nuevoNodo->sig=NULL;
           if(raizPalabrasReservadas==NULL){
               raizPalabrasReservadas=nuevoNodo;
           }else{
                fondoPalabrasReservadas->sig=nuevoNodo;
           }
          fondoPalabrasReservadas=nuevoNodo;
    }else if(categoria==3){   //OCTAL
          decimal=conversorADecimal(informacionNueva,8);
          NodoConstanteOctal *nuevoNodo;
          nuevoNodo=malloc(sizeof(struct nodoConstanteOctal));
          nuevoNodo->datoEnOctal=strdup(informacionNueva);
          nuevoNodo->decimal=conversorADecimal(informacionNueva,8);
          nuevoNodo->sig=NULL;
          if(raizConstanteOctal==NULL){
               raizConstanteOctal=nuevoNodo;
          }else{
                fondoConstanteOctal->sig=nuevoNodo;
          }
          fondoConstanteOctal=nuevoNodo;
    }else if(categoria==4){   //HEXA  EL RESTO ES SUPER PARECIDO SOLO Q CAMBIAMOS UNAS COSITAS NOMAS
          decimal=conversorADecimal(informacionNueva,16);
          NodoConstanteHexa *nuevoNodo;
          nuevoNodo=malloc(sizeof(struct nodoConstanteHexa));
          nuevoNodo->datoEnHexa=strdup(informacionNueva);
          nuevoNodo->decimal=conversorADecimal(informacionNueva,16);
          nuevoNodo->sig=NULL;
          if(raizConstanteHexa==NULL){
               raizConstanteHexa=nuevoNodo;
          }else{
                fondoConstanteHexa->sig=nuevoNodo;
          }
          fondoConstanteHexa=nuevoNodo;

    }else if(categoria==5){  //DECIMAL
            NodoConstanteDecimal *nuevoNodo;
            nuevoNodo=malloc(sizeof(NodoConstanteDecimal));
            nuevoNodo->decimal=atoi(informacionNueva);
            nuevoNodo->sig=NULL;
            if(raizConstanteDecimal==NULL){
               raizConstanteDecimal=nuevoNodo;
               
            }else{
                fondoConstanteDecimal->sig=nuevoNodo;    
            }
            fondoConstanteDecimal=nuevoNodo;

    }else if(categoria==6){  //REALES
            NodoConstanteReal *nuevoNodo;
            nuevoNodo=malloc(sizeof(NodoConstanteReal));
            float num=strtof(informacionNueva, NULL);
            int parteEn = (int)num;
            nuevoNodo->mantiza=num-parteEn;
            nuevoNodo->parteEntera=parteEn;
            nuevoNodo->sig=NULL;
            if(raizConstanteReal==NULL){
               raizConstanteReal=nuevoNodo;
               
            }else{
                fondoConstanteReal->sig=nuevoNodo;    
            }
            fondoConstanteReal=nuevoNodo;



    }else if(categoria==7){  //CARACTERES 
            NodoConstanteCaracter *nuevoNodo;
            nuevoNodo=malloc(sizeof(NodoConstanteCaracter));
            nuevoNodo->caracter=strdup(informacionNueva);
            if(raizConstanteCaracter==NULL){
               raizConstanteCaracter=nuevoNodo;
            }else{
                fondoConstanteCaracter->sig=nuevoNodo;
            }
            fondoConstanteCaracter=nuevoNodo;

    }else if(categoria==8){  //OPERADORES/CARACTERES DE PUNTUACIÓN
            NodoOperOCaractPunt *recorridoOC,*nuevoNodo;
            recorridoOC=raizOperOCaractPunt;
            if(raizOperOCaractPunt==NULL){
                 nuevoNodo=malloc(sizeof(NodoOperOCaractPunt));
                 nuevoNodo->caracter=strdup(informacionNueva);
                 nuevoNodo->cantidadOperOCaractPunt=1;
                 nuevoNodo->sig=NULL;
                 raizOperOCaractPunt=nuevoNodo;
                 fondoOperOCaractPunt=nuevoNodo;
            }else{
                 while(recorridoOC!=NULL&& strcmp(informacionNueva,recorridoOC->caracter)!=0){
                    recorridoOC=recorridoOC->sig;    
                 }
                 if(recorridoOC==NULL){
                    nuevoNodo=malloc(sizeof(NodoOperOCaractPunt));
                    nuevoNodo->caracter=strdup(informacionNueva);
                    nuevoNodo->cantidadOperOCaractPunt=1;
                    nuevoNodo->sig=NULL;
                    fondoOperOCaractPunt->sig=nuevoNodo;
                    fondoOperOCaractPunt=nuevoNodo;
                }else{
                    (recorridoOC->cantidadOperOCaractPunt)++;
                }
            }

    }else if(categoria==9){  //COMENTARIOS 
           NodoComentario *nuevoNodo;
           nuevoNodo=malloc(sizeof(struct nodoComentario));
           nuevoNodo->comentario=strdup(informacionNueva);
           nuevoNodo->tipo=strdup(tipo);
           nuevoNodo->sig=NULL;
           if(raizComentario==NULL){
               raizComentario=nuevoNodo;
           }else{
                fondoComentario->sig=nuevoNodo;
           }
          fondoComentario=nuevoNodo;

    }else{
         NodoNoReconocidos *nuevoNodo;
         nuevoNodo=malloc(sizeof(struct nodoNoReconocidos));
         nuevoNodo->noReconocido=strdup(informacionNueva);
         nuevoNodo->linea=cantidadDeLineas;
         nuevoNodo->sig=NULL;
         if(raizNoReconocidos==NULL){
               raizNoReconocidos=nuevoNodo;
         }else{
               fondoNoReconocidos->sig=nuevoNodo;
         }
         fondoNoReconocidos=nuevoNodo;
    }
}



long conversorADecimal(char* informacionNueva,int base){
   long repredecimal=0;
   int longitud;
   longitud = strlen(informacionNueva);
   longitud--;
   int recorrido=longitud;
   for(;recorrido>=0;recorrido--){
        repredecimal+=pow(base,longitud-recorrido)*representacionDigito(*(informacionNueva+recorrido),base);     
   }
   return repredecimal;
}

int representacionDigito(char digito,int base)
{
    if(base==16)
    {   
        switch(digito)
        {   case 'a':
            case 'A':
                return 10;
                break;
            case 'b':
            case 'B':
                return 11;
                break;
            case 'c':
            case 'C':
                return 12;
                break;
            case 'd':
            case 'D':
                return 13;
                break;
            case 'e':
            case 'E':
                return 14;
                break;
            case 'f':
            case 'F':
                 return 15;
                 break;    
            default:
                 if(digito>=48&&digito<=57){  
                 return digito-48;
                 break; 
                 }
                 else{
                  return 0;
                  break; 
                 }
                 
        }
    }else{
            return digito-48;
    }
} 


void cuentaSaltos(char* palabra){    
    int largo=strlen(palabra);
    char copia[largo+1];
    strcpy(copia,palabra);
    int i;
    for(i=0;i<=largo;i++){
        if(copia[i]=='\n'){
            cantidadDeLineas++;
        }
    }
}

#line 890 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 423 "tp3.l"



#line 1045 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 150 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 252 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 426 "tp3.l"
{agregarNodo(1,yytext," ");cuentaSaltos(yytext);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 428 "tp3.l"
{agregarNodo(3,yytext,"");cuentaSaltos(yytext);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 429 "tp3.l"
{agregarNodo(4,yytext,"");cuentaSaltos(yytext);} 
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 430 "tp3.l"
{agregarNodo(5,yytext,"");cuentaSaltos(yytext);} 
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 431 "tp3.l"
{agregarNodo(7,yytext," ");cuentaSaltos(yytext);} 
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 432 "tp3.l"
{agregarNodo(8,yytext," ");cuentaSaltos(yytext);} 
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 433 "tp3.l"
{agregarNodo(2,yytext,"de dato");cuentaSaltos(yytext);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 434 "tp3.l"
{agregarNodo(2,yytext," de control");cuentaSaltos(yytext);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 435 "tp3.l"
{agregarNodo(2,yytext,"otros");cuentaSaltos(yytext);}  
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 436 "tp3.l"
{agregarNodo(0,yytext," ");cuentaSaltos(yytext);} 
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 438 "tp3.l"
{agregarNodo(6,yytext,"");cuentaSaltos(yytext);} 
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 439 "tp3.l"
{agregarNodo(6,yytext,"");cuentaSaltos(yytext);}
	YY_BREAK
case 13:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 441 "tp3.l"
{agregarNodo(9,yytext,"simple");cuentaSaltos(yytext);} 
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 442 "tp3.l"
{agregarNodo(9,yytext,"multiple");cuentaSaltos(yytext);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 443 "tp3.l"
{agregarNodo(10,yytext,"");cuentaSaltos(yytext);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 444 "tp3.l"
ECHO;
	YY_BREAK
#line 1211 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 150 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 150 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 149);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 444 "tp3.l"

int main(void) { 
    
    yyin=fopen("archivo.c","r");
    yylex();
    NodoIdentificadores *recorridoI;
    recorridoI=raizIdentificadores;
    printf("              REPORTE TOKENS DENTRO DE ARCHIVO archivo.c\n");
    printf("................................................................\n");
    while(recorridoI!=NULL){
       printf("el identificador llamado %s ",recorridoI->identificador);
       printf("aparece %d vez/veces.\n",recorridoI->cantidadIdentificadores);

       recorridoI=recorridoI->sig;
    }
    if(raizLiteralCadena!=NULL){
        printf("................................................................\n");
    }

    NodoLiteralCadena *recorridoLC;
    recorridoLC=raizLiteralCadena;
    while(recorridoLC!=NULL){
       printf("el literal cadena %s",recorridoLC->literalCadena);
       printf(" tiene un largo de %d. \n",recorridoLC->longitud);
       recorridoLC=recorridoLC->sig;
    }
    
    if(raizPalabrasReservadas!=NULL){
        printf("................................................................\n");
    }

    NodoPalabrasReservadas *recorridoPR;
    recorridoPR=raizPalabrasReservadas;
    while(recorridoPR!=NULL){
       printf("La palabra reservada %s",recorridoPR->palabraReservada);
       printf(" es del tipo  %s. \n",recorridoPR->tipo);
       recorridoPR=recorridoPR->sig;
    }
    if(raizConstanteOctal!=NULL){
        printf("................................................................\n");
    }
    NodoConstanteOctal *recorridoCO;
    recorridoCO=raizConstanteOctal;
    while(recorridoCO!=NULL){
       printf("La constante octal %s",recorridoCO->datoEnOctal);
       printf(" equivale %d en decimal.\n",recorridoCO->decimal);
       recorridoCO=recorridoCO->sig;
    }
    if(raizConstanteHexa!=NULL){
        printf("................................................................\n");
    }
    NodoConstanteHexa *recorridoCH;
    recorridoCH=raizConstanteHexa;
    while(recorridoCH!=NULL){
       printf("La constante hexa %s",recorridoCH->datoEnHexa);
       printf(" equivale %d en decimal. \n",recorridoCH->decimal);
       recorridoCH=recorridoCH->sig;
    }
    if(raizConstanteDecimal!=NULL){
        printf("................................................................\n");
    }
    NodoConstanteDecimal *recorridoD;
    recorridoD=raizConstanteDecimal;
    int total=0;
    while(recorridoD!=NULL){
       printf("Se encuentra el decimal %d. \n",recorridoD->decimal);
       total=total+recorridoD->decimal;
       recorridoD=recorridoD->sig;

    }
    if(raizConstanteDecimal!=NULL){
        printf("Sumando un total de %d. \n",total);
    }
    if(raizConstanteReal!=NULL){
        printf("................................................................\n");
    }

    NodoConstanteReal *recorridoR;
    recorridoR=raizConstanteReal;
    while(recorridoR!=NULL){
       printf("El valor entero %d ",recorridoR->parteEntera);
       printf(" con mantiza %f. \n",recorridoR->mantiza);
       recorridoR=recorridoR->sig;
    }
    if(raizConstanteCaracter!=NULL){
        printf("................................................................\n");
    }
    NodoConstanteCaracter *recorridoC;
    recorridoC=raizConstanteCaracter;
    int enumeracion=1;
    while(recorridoC!=NULL){
      printf("%i aaaaaa",enumeracion);
      printf(" El caracter %s.\n",recorridoC->caracter);
      enumeracion++;
      recorridoC=recorridoC->sig;    
    }
    if(raizOperOCaractPunt!=NULL){
        printf("................................................................\n");
    }
    NodoOperOCaractPunt *recorridoCP;
    recorridoCP=raizOperOCaractPunt;
    while(recorridoCP!=NULL){
       printf("El caracter de operacion o puntutacion %s ",recorridoCP->caracter);
       printf("aparece %d veces.\n",recorridoCP->cantidadOperOCaractPunt);

       recorridoCP=recorridoCP->sig;
    }
    if(raizComentario!=NULL){
        printf("................................................................\n");
    }
    NodoComentario *recorridoComen;
    recorridoComen=raizComentario;
    while(recorridoComen!=NULL){
      if(strcmp("simple",recorridoComen->tipo)==0){
           printf("El comentario %s",recorridoComen->comentario+2);
           printf(" es de tipo %s \n",recorridoComen->tipo);
      }else{
           int largo,i,recorrido=0;
           largo=strlen(recorridoComen->comentario);
           char copia[largo+1];
           strcpy(copia,recorridoComen->comentario);
           while(copia[recorrido]!='\0'){
               if(copia[recorrido]=='\n'){
                   for(i=recorrido;i<largo;i++){
                       copia[i]=copia[i+1];
                   }
                   largo--;
               }
               recorrido++;
            }  
            int largoCopia=strlen(copia);
            int j;
            for(j=0;j<=largoCopia;j++){
                if(j==largoCopia-2){
                    copia[j]='\0';
                }
            }
            printf("El comentario %s",copia+2);
            printf(" es de tipo %s. \n",recorridoComen->tipo);
       }       
        recorridoComen=recorridoComen->sig;
    }
    printf("................................................................\n");
   /*
    NodoNoReconocidos *recorridoNR;
    recorridoNR=raizNoReconocidos;
    while(recorridoNR!=NULL){
       printf("El cadenas y/o caracteres no reconocidos %s ",recorridoNR->noReconocido);
       printf("aparece en la linea %d.\n",recorridoNR->linea);

       recorridoNR=recorridoNR->sig;
    }
    if(raizNoReconocidos!=NULL){
        printf("................................................................\n");
    }
    */

    
    system("pause");
    return 0;
} 

